/**
 * codeExportClient — client-side FULL-PROJECT bundler using Vite's
 * import.meta.glob. Produces a single JSON that can fully restore the
 * project (frontend + backend python assets + supabase migrations +
 * public binary assets + root config + restore guide).
 *
 * Text files → inlined as UTF-8 strings.
 * Binary files (png/ico/woff/…) → inlined as base64 with `encoding: "base64"`.
 */

export interface ExportedFile {
  path: string;
  bytes: number;
  content: string;
  encoding?: "utf8" | "base64";
}

export interface IntegrityCheck {
  ok: boolean;
  missing: string[];
  missingGlobs: string[];
  minCounts: Record<string, { required: number; found: number }>;
  totalFiles: number;
  totalBytes: number;
}

export interface CodeExportBundle {
  generatedAt: string;
  project: string;
  fileCount: number;
  totalBytes: number;
  files: ExportedFile[];
  manifest: Array<{ path: string; bytes: number; encoding: "utf8" | "base64" }>;
  restoreGuide: string;
  integrity: IntegrityCheck;
}

export class IntegrityError extends Error {
  constructor(public report: IntegrityCheck) {
    super(
      `Backup integrity check failed — missing ${report.missing.length} required file(s)` +
        (report.missingGlobs.length ? `, ${report.missingGlobs.length} empty required folder(s)` : ""),
    );
    this.name = "IntegrityError";
  }
}

// ---------- TEXT SOURCES (inlined as strings) ----------
const TEXT_MODULES = {
  ...(import.meta.glob(
    [
      "/src/**/*.{ts,tsx,js,jsx,css,scss,md,json,sql,html,svg,py,txt,yml,yaml,toml,cfg,ini,env}",
      "/src/**/*.ts.txt",
      "!/src/routeTree.gen.ts",
    ],
    { query: "?raw", import: "default", eager: true },
  ) as Record<string, string>),
  ...(import.meta.glob("/supabase/**/*.{sql,toml,ts,json,md}", {
    query: "?raw",
    import: "default",
    eager: true,
  }) as Record<string, string>),
  ...(import.meta.glob("/public/**/*.{json,txt,md,svg,html,xml,webmanifest}", {
    query: "?raw",
    import: "default",
    eager: true,
  }) as Record<string, string>),
  ...(import.meta.glob(
    [
      "/*.{ts,js,mjs,cjs,json,jsonc,md,html,yml,yaml,toml,css}",
      "/.{gitignore,env.example,prettierrc,prettierignore}",
    ],
    { query: "?raw", import: "default", eager: true },
  ) as Record<string, string>),
} as Record<string, string>;

// ---------- BINARY ASSETS (inlined as URLs → fetched → base64) ----------
// Vite treats these as asset URLs; we fetch them at runtime and base64-encode
// so the JSON bundle is fully self-contained (icons, fonts, images).
const BINARY_URLS = {
  ...(import.meta.glob("/public/**/*.{png,jpg,jpeg,gif,webp,ico,woff,woff2,ttf,otf}", {
    query: "?url",
    import: "default",
    eager: true,
  }) as Record<string, string>),
  ...(import.meta.glob("/src/**/*.{png,jpg,jpeg,gif,webp,ico,woff,woff2,ttf,otf}", {
    query: "?url",
    import: "default",
    eager: true,
  }) as Record<string, string>),
} as Record<string, string>;

async function fetchAsBase64(url: string): Promise<{ base64: string; bytes: number } | null> {
  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    const buf = await res.arrayBuffer();
    const bytes = buf.byteLength;
    // chunked base64 to avoid stack overflow for large files
    const u8 = new Uint8Array(buf);
    let binary = "";
    const chunk = 0x8000;
    for (let i = 0; i < u8.length; i += chunk) {
      binary += String.fromCharCode(...u8.subarray(i, i + chunk));
    }
    return { base64: btoa(binary), bytes };
  } catch {
    return null;
  }
}

const RESTORE_GUIDE = `# Full Restore Guide — AI Executive OS / OferTradingBot

This JSON is a self-contained snapshot of the whole project. To rebuild after
a deletion:

1. Create an empty project folder.
2. For every entry in \`files[]\`:
   - If \`encoding === "base64"\` → decode and write as binary.
   - Else write \`content\` as UTF-8 to \`path\` (relative to project root).
3. Install deps:  \`bun install\`  (or \`npm install\`).
4. Restore Supabase:
   - Create a new Lovable Cloud / Supabase project.
   - Run every SQL under \`supabase/migrations/\` in filename order.
   - Set env vars \`VITE_SUPABASE_URL\`, \`VITE_SUPABASE_PUBLISHABLE_KEY\`,
     \`VITE_SUPABASE_PROJECT_ID\` in \`.env\`.
5. Backend (optional local FastAPI on :8050):
   - Copy \`src/assets/backend/\` and \`src/assets/hub/\` out to a working dir.
   - \`pip install -r requirements.txt\` then \`python main.py\`.
6. Dev server: \`bun run dev\`.

Contents guaranteed:
- All /src source (ts, tsx, css, py, json, md, svg, txt)
- Supabase config + all migrations
- Public assets including PNG icons (base64)
- Root config: package.json, tsconfig, vite.config, wrangler, eslint, components.json, bunfig, prettier, README

Excluded (regeneratable / secret):
- node_modules, dist, .wrangler, .git
- bun.lockb (run \`bun install\` to regenerate)
- .env with live secrets (recreate via Lovable Cloud connect)
- src/routeTree.gen.ts (auto-generated by TanStack Router on dev start)
`;

export async function buildCodeBundle(projectName = "ai-executive-os"): Promise<CodeExportBundle> {
  const files: ExportedFile[] = [];
  let total = 0;

  // text
  for (const [absPath, raw] of Object.entries(TEXT_MODULES)) {
    if (typeof raw !== "string") continue;
    const path = absPath.replace(/^\//, "");
    const bytes = new Blob([raw]).size;
    files.push({ path, bytes, content: raw, encoding: "utf8" });
    total += bytes;
  }

  // binary
  for (const [absPath, url] of Object.entries(BINARY_URLS)) {
    const path = absPath.replace(/^\//, "");
    const b = await fetchAsBase64(url);
    if (!b) continue;
    files.push({ path, bytes: b.bytes, content: b.base64, encoding: "base64" });
    total += b.bytes;
  }

  // restore guide
  const guideBytes = new Blob([RESTORE_GUIDE]).size;
  files.push({ path: "RESTORE.md", bytes: guideBytes, content: RESTORE_GUIDE, encoding: "utf8" });
  total += guideBytes;

  files.sort((a, b) => a.path.localeCompare(b.path));

  return {
    generatedAt: new Date().toISOString(),
    project: projectName,
    fileCount: files.length,
    totalBytes: total,
    files,
    manifest: files.map((f) => ({ path: f.path, bytes: f.bytes, encoding: f.encoding ?? "utf8" })),
    restoreGuide: RESTORE_GUIDE,
  };
}
