/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistsRouteImport } from './routes/watchlists'
import { Route as TriggersRouteImport } from './routes/triggers'
import { Route as TradingRouteImport } from './routes/trading'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as SystemRouteImport } from './routes/system'
import { Route as StrategyRouteImport } from './routes/strategy'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as RepoAnalyzerRouteImport } from './routes/repo-analyzer'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PersonasRouteImport } from './routes/personas'
import { Route as OrderTicketRouteImport } from './routes/order-ticket'
import { Route as MicrostructureRouteImport } from './routes/microstructure'
import { Route as LiveTradingRouteImport } from './routes/live-trading'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as GooseRouteImport } from './routes/goose'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as CommandRouteImport } from './routes/command'
import { Route as CodeStudioRouteImport } from './routes/code-studio'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as BacktestingRouteImport } from './routes/backtesting'
import { Route as ApiVaultRouteImport } from './routes/api-vault'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TickerSymbolRouteImport } from './routes/ticker.$symbol'
import { Route as ApiPublicHooksDriveBackupDailyRouteImport } from './routes/api/public/hooks/drive-backup-daily'

const WatchlistsRoute = WatchlistsRouteImport.update({
  id: '/watchlists',
  path: '/watchlists',
  getParentRoute: () => rootRouteImport,
} as any)
const TriggersRoute = TriggersRouteImport.update({
  id: '/triggers',
  path: '/triggers',
  getParentRoute: () => rootRouteImport,
} as any)
const TradingRoute = TradingRouteImport.update({
  id: '/trading',
  path: '/trading',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoAnalyzerRoute = RepoAnalyzerRouteImport.update({
  id: '/repo-analyzer',
  path: '/repo-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonasRoute = PersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderTicketRoute = OrderTicketRouteImport.update({
  id: '/order-ticket',
  path: '/order-ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const MicrostructureRoute = MicrostructureRouteImport.update({
  id: '/microstructure',
  path: '/microstructure',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveTradingRoute = LiveTradingRouteImport.update({
  id: '/live-trading',
  path: '/live-trading',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const GooseRoute = GooseRouteImport.update({
  id: '/goose',
  path: '/goose',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoute = CommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeStudioRoute = CodeStudioRouteImport.update({
  id: '/code-studio',
  path: '/code-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestingRoute = BacktestingRouteImport.update({
  id: '/backtesting',
  path: '/backtesting',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVaultRoute = ApiVaultRouteImport.update({
  id: '/api-vault',
  path: '/api-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TickerSymbolRoute = TickerSymbolRouteImport.update({
  id: '/ticker/$symbol',
  path: '/ticker/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDriveBackupDailyRoute =
  ApiPublicHooksDriveBackupDailyRouteImport.update({
    id: '/api/public/hooks/drive-backup-daily',
    path: '/api/public/hooks/drive-backup-daily',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/alerts': typeof AlertsRoute
  '/api-vault': typeof ApiVaultRoute
  '/backtesting': typeof BacktestingRoute
  '/backup': typeof BackupRoute
  '/code-studio': typeof CodeStudioRoute
  '/command': typeof CommandRoute
  '/config': typeof ConfigRoute
  '/goose': typeof GooseRoute
  '/intelligence': typeof IntelligenceRoute
  '/journal': typeof JournalRoute
  '/live-trading': typeof LiveTradingRoute
  '/microstructure': typeof MicrostructureRoute
  '/order-ticket': typeof OrderTicketRoute
  '/personas': typeof PersonasRoute
  '/portfolio': typeof PortfolioRoute
  '/repo-analyzer': typeof RepoAnalyzerRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/strategy': typeof StrategyRoute
  '/system': typeof SystemRoute
  '/terminal': typeof TerminalRoute
  '/trading': typeof TradingRoute
  '/triggers': typeof TriggersRoute
  '/watchlists': typeof WatchlistsRoute
  '/ticker/$symbol': typeof TickerSymbolRoute
  '/api/public/hooks/drive-backup-daily': typeof ApiPublicHooksDriveBackupDailyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/alerts': typeof AlertsRoute
  '/api-vault': typeof ApiVaultRoute
  '/backtesting': typeof BacktestingRoute
  '/backup': typeof BackupRoute
  '/code-studio': typeof CodeStudioRoute
  '/command': typeof CommandRoute
  '/config': typeof ConfigRoute
  '/goose': typeof GooseRoute
  '/intelligence': typeof IntelligenceRoute
  '/journal': typeof JournalRoute
  '/live-trading': typeof LiveTradingRoute
  '/microstructure': typeof MicrostructureRoute
  '/order-ticket': typeof OrderTicketRoute
  '/personas': typeof PersonasRoute
  '/portfolio': typeof PortfolioRoute
  '/repo-analyzer': typeof RepoAnalyzerRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/strategy': typeof StrategyRoute
  '/system': typeof SystemRoute
  '/terminal': typeof TerminalRoute
  '/trading': typeof TradingRoute
  '/triggers': typeof TriggersRoute
  '/watchlists': typeof WatchlistsRoute
  '/ticker/$symbol': typeof TickerSymbolRoute
  '/api/public/hooks/drive-backup-daily': typeof ApiPublicHooksDriveBackupDailyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/alerts': typeof AlertsRoute
  '/api-vault': typeof ApiVaultRoute
  '/backtesting': typeof BacktestingRoute
  '/backup': typeof BackupRoute
  '/code-studio': typeof CodeStudioRoute
  '/command': typeof CommandRoute
  '/config': typeof ConfigRoute
  '/goose': typeof GooseRoute
  '/intelligence': typeof IntelligenceRoute
  '/journal': typeof JournalRoute
  '/live-trading': typeof LiveTradingRoute
  '/microstructure': typeof MicrostructureRoute
  '/order-ticket': typeof OrderTicketRoute
  '/personas': typeof PersonasRoute
  '/portfolio': typeof PortfolioRoute
  '/repo-analyzer': typeof RepoAnalyzerRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/strategy': typeof StrategyRoute
  '/system': typeof SystemRoute
  '/terminal': typeof TerminalRoute
  '/trading': typeof TradingRoute
  '/triggers': typeof TriggersRoute
  '/watchlists': typeof WatchlistsRoute
  '/ticker/$symbol': typeof TickerSymbolRoute
  '/api/public/hooks/drive-backup-daily': typeof ApiPublicHooksDriveBackupDailyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/alerts'
    | '/api-vault'
    | '/backtesting'
    | '/backup'
    | '/code-studio'
    | '/command'
    | '/config'
    | '/goose'
    | '/intelligence'
    | '/journal'
    | '/live-trading'
    | '/microstructure'
    | '/order-ticket'
    | '/personas'
    | '/portfolio'
    | '/repo-analyzer'
    | '/security'
    | '/settings'
    | '/strategy'
    | '/system'
    | '/terminal'
    | '/trading'
    | '/triggers'
    | '/watchlists'
    | '/ticker/$symbol'
    | '/api/public/hooks/drive-backup-daily'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/alerts'
    | '/api-vault'
    | '/backtesting'
    | '/backup'
    | '/code-studio'
    | '/command'
    | '/config'
    | '/goose'
    | '/intelligence'
    | '/journal'
    | '/live-trading'
    | '/microstructure'
    | '/order-ticket'
    | '/personas'
    | '/portfolio'
    | '/repo-analyzer'
    | '/security'
    | '/settings'
    | '/strategy'
    | '/system'
    | '/terminal'
    | '/trading'
    | '/triggers'
    | '/watchlists'
    | '/ticker/$symbol'
    | '/api/public/hooks/drive-backup-daily'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/alerts'
    | '/api-vault'
    | '/backtesting'
    | '/backup'
    | '/code-studio'
    | '/command'
    | '/config'
    | '/goose'
    | '/intelligence'
    | '/journal'
    | '/live-trading'
    | '/microstructure'
    | '/order-ticket'
    | '/personas'
    | '/portfolio'
    | '/repo-analyzer'
    | '/security'
    | '/settings'
    | '/strategy'
    | '/system'
    | '/terminal'
    | '/trading'
    | '/triggers'
    | '/watchlists'
    | '/ticker/$symbol'
    | '/api/public/hooks/drive-backup-daily'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  AlertsRoute: typeof AlertsRoute
  ApiVaultRoute: typeof ApiVaultRoute
  BacktestingRoute: typeof BacktestingRoute
  BackupRoute: typeof BackupRoute
  CodeStudioRoute: typeof CodeStudioRoute
  CommandRoute: typeof CommandRoute
  ConfigRoute: typeof ConfigRoute
  GooseRoute: typeof GooseRoute
  IntelligenceRoute: typeof IntelligenceRoute
  JournalRoute: typeof JournalRoute
  LiveTradingRoute: typeof LiveTradingRoute
  MicrostructureRoute: typeof MicrostructureRoute
  OrderTicketRoute: typeof OrderTicketRoute
  PersonasRoute: typeof PersonasRoute
  PortfolioRoute: typeof PortfolioRoute
  RepoAnalyzerRoute: typeof RepoAnalyzerRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  StrategyRoute: typeof StrategyRoute
  SystemRoute: typeof SystemRoute
  TerminalRoute: typeof TerminalRoute
  TradingRoute: typeof TradingRoute
  TriggersRoute: typeof TriggersRoute
  WatchlistsRoute: typeof WatchlistsRoute
  TickerSymbolRoute: typeof TickerSymbolRoute
  ApiPublicHooksDriveBackupDailyRoute: typeof ApiPublicHooksDriveBackupDailyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlists': {
      id: '/watchlists'
      path: '/watchlists'
      fullPath: '/watchlists'
      preLoaderRoute: typeof WatchlistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triggers': {
      id: '/triggers'
      path: '/triggers'
      fullPath: '/triggers'
      preLoaderRoute: typeof TriggersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trading': {
      id: '/trading'
      path: '/trading'
      fullPath: '/trading'
      preLoaderRoute: typeof TradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo-analyzer': {
      id: '/repo-analyzer'
      path: '/repo-analyzer'
      fullPath: '/repo-analyzer'
      preLoaderRoute: typeof RepoAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personas': {
      id: '/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof PersonasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-ticket': {
      id: '/order-ticket'
      path: '/order-ticket'
      fullPath: '/order-ticket'
      preLoaderRoute: typeof OrderTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/microstructure': {
      id: '/microstructure'
      path: '/microstructure'
      fullPath: '/microstructure'
      preLoaderRoute: typeof MicrostructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-trading': {
      id: '/live-trading'
      path: '/live-trading'
      fullPath: '/live-trading'
      preLoaderRoute: typeof LiveTradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goose': {
      id: '/goose'
      path: '/goose'
      fullPath: '/goose'
      preLoaderRoute: typeof GooseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code-studio': {
      id: '/code-studio'
      path: '/code-studio'
      fullPath: '/code-studio'
      preLoaderRoute: typeof CodeStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtesting': {
      id: '/backtesting'
      path: '/backtesting'
      fullPath: '/backtesting'
      preLoaderRoute: typeof BacktestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-vault': {
      id: '/api-vault'
      path: '/api-vault'
      fullPath: '/api-vault'
      preLoaderRoute: typeof ApiVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticker/$symbol': {
      id: '/ticker/$symbol'
      path: '/ticker/$symbol'
      fullPath: '/ticker/$symbol'
      preLoaderRoute: typeof TickerSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/drive-backup-daily': {
      id: '/api/public/hooks/drive-backup-daily'
      path: '/api/public/hooks/drive-backup-daily'
      fullPath: '/api/public/hooks/drive-backup-daily'
      preLoaderRoute: typeof ApiPublicHooksDriveBackupDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  AlertsRoute: AlertsRoute,
  ApiVaultRoute: ApiVaultRoute,
  BacktestingRoute: BacktestingRoute,
  BackupRoute: BackupRoute,
  CodeStudioRoute: CodeStudioRoute,
  CommandRoute: CommandRoute,
  ConfigRoute: ConfigRoute,
  GooseRoute: GooseRoute,
  IntelligenceRoute: IntelligenceRoute,
  JournalRoute: JournalRoute,
  LiveTradingRoute: LiveTradingRoute,
  MicrostructureRoute: MicrostructureRoute,
  OrderTicketRoute: OrderTicketRoute,
  PersonasRoute: PersonasRoute,
  PortfolioRoute: PortfolioRoute,
  RepoAnalyzerRoute: RepoAnalyzerRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  StrategyRoute: StrategyRoute,
  SystemRoute: SystemRoute,
  TerminalRoute: TerminalRoute,
  TradingRoute: TradingRoute,
  TriggersRoute: TriggersRoute,
  WatchlistsRoute: WatchlistsRoute,
  TickerSymbolRoute: TickerSymbolRoute,
  ApiPublicHooksDriveBackupDailyRoute: ApiPublicHooksDriveBackupDailyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
