/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as SystemRouteImport } from './routes/system'
import { Route as StrategyRouteImport } from './routes/strategy'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PersonasRouteImport } from './routes/personas'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as ApiVaultRouteImport } from './routes/api-vault'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'

const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonasRoute = PersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVaultRoute = ApiVaultRouteImport.update({
  id: '/api-vault',
  path: '/api-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/api-vault': typeof ApiVaultRoute
  '/backup': typeof BackupRoute
  '/config': typeof ConfigRoute
  '/intelligence': typeof IntelligenceRoute
  '/personas': typeof PersonasRoute
  '/settings': typeof SettingsRoute
  '/strategy': typeof StrategyRoute
  '/system': typeof SystemRoute
  '/terminal': typeof TerminalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/api-vault': typeof ApiVaultRoute
  '/backup': typeof BackupRoute
  '/config': typeof ConfigRoute
  '/intelligence': typeof IntelligenceRoute
  '/personas': typeof PersonasRoute
  '/settings': typeof SettingsRoute
  '/strategy': typeof StrategyRoute
  '/system': typeof SystemRoute
  '/terminal': typeof TerminalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/api-vault': typeof ApiVaultRoute
  '/backup': typeof BackupRoute
  '/config': typeof ConfigRoute
  '/intelligence': typeof IntelligenceRoute
  '/personas': typeof PersonasRoute
  '/settings': typeof SettingsRoute
  '/strategy': typeof StrategyRoute
  '/system': typeof SystemRoute
  '/terminal': typeof TerminalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/api-vault'
    | '/backup'
    | '/config'
    | '/intelligence'
    | '/personas'
    | '/settings'
    | '/strategy'
    | '/system'
    | '/terminal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/api-vault'
    | '/backup'
    | '/config'
    | '/intelligence'
    | '/personas'
    | '/settings'
    | '/strategy'
    | '/system'
    | '/terminal'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/api-vault'
    | '/backup'
    | '/config'
    | '/intelligence'
    | '/personas'
    | '/settings'
    | '/strategy'
    | '/system'
    | '/terminal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  ApiVaultRoute: typeof ApiVaultRoute
  BackupRoute: typeof BackupRoute
  ConfigRoute: typeof ConfigRoute
  IntelligenceRoute: typeof IntelligenceRoute
  PersonasRoute: typeof PersonasRoute
  SettingsRoute: typeof SettingsRoute
  StrategyRoute: typeof StrategyRoute
  SystemRoute: typeof SystemRoute
  TerminalRoute: typeof TerminalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personas': {
      id: '/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof PersonasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-vault': {
      id: '/api-vault'
      path: '/api-vault'
      fullPath: '/api-vault'
      preLoaderRoute: typeof ApiVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  ApiVaultRoute: ApiVaultRoute,
  BackupRoute: BackupRoute,
  ConfigRoute: ConfigRoute,
  IntelligenceRoute: IntelligenceRoute,
  PersonasRoute: PersonasRoute,
  SettingsRoute: SettingsRoute,
  StrategyRoute: StrategyRoute,
  SystemRoute: SystemRoute,
  TerminalRoute: TerminalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
